### ISSUE TITLE
Time limit

### ISSUE THREAD

**Issue by carlhannes** [qlik-oss/core-chopper#38]
It would be great with some kind of time limit, or difficulty increase with time, in case someone keeps biking for very long

**Comment by peol** [comment]
We've been discussing time limit on a secondary (more skill-based) game mode. The current one gets harder the higher you go, but we should likely keep the hardest difficulty you've reached so you don't plateau and keep biking on a specific level (though, that gives you nothing since you cannot win). Not too fond of a time limit here since it can instead stop a potential high score due to time.

Has it been a problem thus far? Not something I've observed (especially not once they know it's highest point wins).

**Comment by rjriel** [comment]
Although the current high score way of doing things is great, we've taken the bike/game to couple of high traffic conferences/hackathons and have seen a need to put a time limit on it. The last hackathon we did was "who can get the highest score in 30s" which still proved fun for the conference goers, but results were somewhat skewed since it was more of a "stop peddling after 30s, let the helicopter crash, oops I forgot the timer" type situation. A variable changing game modes between timed and the current way would be great.

**Comment by peol** [comment]
Fair enough, I think the main issue I have with "give it your all for X seconds" is that people don't really want to sweat (especially not if they're in a suit). I'd prefer a more skill-based one primarily because it's more accessible.

**Comment by rjriel** [comment]
I originally thought that too, but you'd be surprised the effort people are willing to put in when their pride is on the line, we had quite a few people we had to remind not to stand up on the bike

**Comment by peol** [comment]
Cool, maybe NA people are more prone to give a mode like that ago, that hasn't been our experience in EU I think. Nevertheless, an extra mode can't hurt!

**Comment by sublibra** [comment]
WON'T DO: Repository archived
